version: "3.7"

networks:
  db-net:
    name: db-net
    driver: bridge

services:
  mongo:
    image: mongo:latest
    container_name: gatekeeper-mongo.local
    hostname: gatekeeper-mongo.local
    ports:
      - 27017:27017
    networks:
      - db-net
